from dotenv import dotenv_values


def create_built_secrets():
    # .env 파일이 없으면 빈 딕셔너리 반환
    env_vars = dotenv_values(".env")

    with open("built_secrets.py", "w", encoding="utf-8") as f:
        f.write("# This file is auto-generated by build_secrets.py\n")
        f.write("import os\n\n")
        f.write("def load_secrets():\n")

        if not env_vars:
            f.write("    pass\n")
            print("No .env variables found or .env file missing.")
            return

        for key, value in env_vars.items():
            if value is None:
                continue
            # Escape backslashes and single quotes to prevent syntax errors
            safe_value = value.replace("\\", "\\\\").replace("'", "\\'")
            # setdefault를 사용하여 이미 설정된 환경변수(예: 실행 시 로드된 .env)가 있으면 덮어쓰지 않음
            f.write(f"    os.environ.setdefault('{key}', '{safe_value}')\n")


if __name__ == "__main__":
    create_built_secrets()
    print("built_secrets.py created.")
